name: ClearML
base:
  kernel_image: quay.io/testfaster/ignite-kernel
  os_dockerfile: |-
    # This dockerfile defines the base disk image for your VMs
    FROM quay.io/testfaster/kube-ubuntu
    ENV bump-cache 1
    RUN apt update
    RUN apt install gnupg2 software-properties-common rsync socat -y
    RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
    RUN apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    RUN apt install terraform -y
  docker_bake_script: |-
    # Do things that cache docker images for faster builds,
    # like building a prior version of your software.
    # Docker buildkit cache is preserved!
    #!/bin/bash
    set -euo pipefail
    docker pull busybox:1.32.0
  preload_docker_images: []
    # NB: use:
    #     testctl ssh --tty=false -- docker images --format "{{.Repository}}:{{.Tag}}" |sort |sed 's/^/    - /g'
    # and then remove ':<none>' tags
    # to refresh this list
  prewarm_script: |-
    # This gets run after each individual VM starts up, so
    # start services you need in your tests here and they'll be
    # already running when you testctl get
    #!/bin/bash
    #NODE_NAME=$(kubectl get nodes -o jsonpath='{.items[*].metadata.name}')
    #kubectl label nodes $NODE_NAME app=clearml
    #cat > /etc/docker/daemon.json <<EOL
    #{ 
    #  "default-ulimits": {
    #     "nofile": {
    #         "name": "nofile",
    #         "hard": 65536,
    #         "soft": 1024
    #     },
    #     "memlock":
    #     {
    #         "name": "memlock",
    #         "soft": -1,
    #         "hard": -1
    #     }
    #  }
    #}
    #EOL
    #echo "vm.max_map_count=262144" > /tmp/99-clearml.conf
    #sudo mv /tmp/99-clearml.conf /etc/sysctl.d/99-clearml.conf
    #sudo sysctl -w vm.max_map_count=262144
    #sudo service docker restart

    git clone https://github.com/combinator-ml/terraform-k8s-clearml
    cd terraform-k8s-clearml
    git checkout 22dc5b3bef7c7527e450968eb06a725e8435644a
    terraform init
    terraform apply -auto-approve


  kubernetes_version: v1.18.3

runtime:
  cpus: 4
  memory: 12GB
  disk: 50GB
# How many ready VMs to keep running for instant testctl get
prewarm_pool_size: 0
# Upper bound for pool size, e.g. to keep memory usage sensible
max_pool_size: 1
ports: [30080,30008,30081]
# Timeout VMs after this long. Set to "" if you want to use
# the VMs for long running development purposes rather than
# short-lived CI.
default_lease_timeout: ""
pool_sleep_timeout: "never"
shared: true

launch:
  title: ClearML
  buttons:
    - title: ClearML
      port: 30600
   #- title: Model
   #  port: 30600 <- change this!
  homepage: |
    ## Follow the tutorial below
